config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  resources :packages
  resources :purchases do
    member do
      get 'deals'
    end
  end
  resources :stores
  resources :items do
    collection do
      post 'upload'
    end
  end
  post 'bulk_create', to: 'purchases#bulk_create'
  get 'spreadsheet', to: 'purchases#spreadsheet'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'deals', to: 'items#deals'
  get 'summary', to: 'items#summary'
  get 'shopping_list', to: "items#shopping"
  get 'checkout_preview', to: "packages#checkout"
  post 'checkout', to: "packages#checkout", as: :checkout
  # Defines the root path route ("/")
  root "home#index"
end

app/models/store.rb
# == Schema Information
#
# Table name: stores
#
#  id         :bigint           not null, primary key
#  deleted    :boolean          default(FALSE)
#  location   :point
#  name       :string           not null
#  owner      :string
#  place      :string
#  created_at :datetime         not null
#
class Store < ApplicationRecord
  has_many :purchases

  def to_s
    "#{name} #{place}"
  end

  def self.listings
    JSON.generate all.map.to_h { |store| [store.name, store.to_s] }
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: %i[ show edit update destroy ]

  # GET /stores or /stores.json
  def index
    @stores = Store.all

    @stores = @stores.where(location: params[:location]) if params[:location]
  end

  # GET /stores/1 or /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores or /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to store_url(@store), notice: "Store was successfully created." }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1 or /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to store_url(@store), notice: "Store was successfully updated." }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1 or /stores/1.json
  def destroy
    @store.destroy

    respond_to do |format|
      format.html { redirect_to stores_url, notice: "Store was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def store_params
      params.require(:store).permit(:name, :place, :owner)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store) do |form| %>
  <% if store.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
        <% store.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label(:place, style: "display: block") { 'Location / Area' } %>
    <%= form.text_field :place %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/_store.html.erb
<div id="<%= dom_id store %>">
  <p>
    <strong>Name:</strong>
    <%= store.name %>
  </p>

  <p>
    <strong>Place:</strong>
    <%= store.place %>
  </p>

  <p>
    <strong>Owner:</strong>
    <%= store.owner %>
  </p>

</div>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render "form", store: @store %>

<br>

<div>
  <%= link_to "Show this store", @store %> |
  <%= link_to "Back to stores", stores_path %>
</div>

app/views/stores/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Stores</h1>

<div class="gridable" id="stores">
  <% @stores.each do |store| %>
    <%= link_to(store) do %>
      <%= render store %>
    <% end %>
  <% end %>
</div>

<%= link_to "New store", new_store_path %>

app/views/stores/new.html.erb
<h1>New store</h1>

<%= render "form", store: @store %>

<br>

<div>
  <%= link_to "Back to stores", stores_path %>
</div>

app/views/stores/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @store %>

<div>
  <%= link_to "Edit this store", edit_store_path(@store) %> |
  <%= link_to "Back to stores", stores_path %>

  <%= button_to "Destroy this store", @store, method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }  %>
</div>