config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  resources :packages
  resources :purchases do
    member do
      get 'deals'
    end
  end
  resources :stores
  resources :items do
    collection do
      post 'upload'
    end
  end
  post 'bulk_create', to: 'purchases#bulk_create'
  get 'spreadsheet', to: 'purchases#spreadsheet'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'deals', to: 'items#deals'
  get 'summary', to: 'items#summary'
  get 'shopping_list', to: "items#shopping"
  get 'checkout_preview', to: "packages#checkout"
  post 'checkout', to: "packages#checkout", as: :checkout
  # Defines the root path route ("/")
  root "home#index"
end

app/views/layouts/partials/_editable_table.html.erb
<div data-editable-table-columns-value="<%= Purchase.js_columns %>"
     data-editable-table-stores-value="<%= Store.listings %>"
     data-editable-table-items-value="<%= Item.listings %>"
     data-controller="editable-table">
  <button data-action="editable-table#addRows">Add Rows</button>
  <div data-editable-table-target="container" id="editable-table"></div>
  <button data-action="editable-table#save">Save</button>
</div>
<!-- - let's put this inside a form so it'll have the authenticity token -->

app/views/layouts/partials/_items_and_purchases.html.erb
<h1>Current Shopping Prices in Winnipeg</h1>

<div id="items">
  <h2>Items</h2>
  <div data-table-url-value="/items"
       data-table-columns-value="<%= Item.js_columns %>"
       data-table-height-value="25vh"
       data-table-title-value="Grocery Products"
       data-controller="table">
    <%= render('layouts/partials/tables/export_buttons') %>
      <div data-table-target="container" id="items-table"></div>
  </div>
</div>

<div data-table-url-value="/purchases"
     data-table-columns-value="<%= Purchase.js_columns %>"
     data-table-height-value="35vh"
     data-table-title-value="Purchases"
     data-controller="table">
  <h2>Recent Purchases</h2>
  <%= render('layouts/partials/tables/export_buttons') %>
    <div data-table-target="container" id="purchases-table"></div>
</div>

app/views/layouts/partials/_nav.html.erb
<div class="<%= class_names('flex navbar justify-between', { 'row-reverse': @splash_screen }) %>">
  <%- unless @splash_screen %>
    <%= render('/layouts/partials/nav_links') %>
  <%- end %>
  <div class="purchases">
    <p>
      <%= link_to("All Groceries", items_path) %>
      <label>[+] Add Purchases: </label>
      <%= link_to "Bulk" , spreadsheet_path %> /
      <%= link_to "Single" , new_purchase_path %> |
      <%= link_to "View All" , purchases_path %>
    </p>
  </div>
</div>

app/views/layouts/partials/_nav_links.html.erb
<div class="flex justify-apart">
  <p>
    <%= link_to "Home" , root_path %>
  </p>
  <p>
    <%= link_to "Shopping List" , shopping_list_path %>
  </p>
  <p>
    <%= link_to "Best Deals" , deals_path %>
  </p>
  <p>
    <%= link_to "All Prices" , summary_path %>
  </p>
</div>